// <auto-generated />
namespace SiarheiKuchukIncorporated.HomeWork8.Dal_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedProductDescriptionrequiredcolumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedProductDescriptionrequiredcolumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201607181239252_Added Product.Description required column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
