using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using WebApp15.Database;
using WebApp15.Models;

namespace WebApp15.Api
{
    public class CarsController : ApiController
    {
        // [HttpGet]
        public IEnumerable<Car> Get()
        {
            return DB.Cars;
        }

        public Car Get(int id)
        {
            return DB.Cars.Single(x => x.Id == id);
        }

        public int Post(Car car)
        {
            car.Id = DB.Cars.Max(existingCar => existingCar.Id) + 1;
            DB.Cars.Add(car);
            return car.Id; // id generated by db
        }

        public void Delete(int id)
        {
            var car = DB.Cars.Single(x => x.Id == id);
            DB.Cars.Remove(car);
        }
    }
}
