//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiarheiKuchukIncorporated.HomeWork8.Dal_DbFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShopDbEntities : DbContext
    {
        public ShopDbEntities()
            : base("name=ShopDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Product> Product { get; set; }
    
        public virtual ObjectResult<Categories_Select_Result> Categories_Select(Nullable<int> category_UID)
        {
            var category_UIDParameter = category_UID.HasValue ?
                new ObjectParameter("Category_UID", category_UID) :
                new ObjectParameter("Category_UID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Categories_Select_Result>("Categories_Select", category_UIDParameter);
        }
    
        public virtual ObjectResult<Categories_SelectAll_Result> Categories_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Categories_SelectAll_Result>("Categories_SelectAll");
        }
    
        public virtual ObjectResult<Products_Select_Result> Products_Select(Nullable<int> category_UID)
        {
            var category_UIDParameter = category_UID.HasValue ?
                new ObjectParameter("Category_UID", category_UID) :
                new ObjectParameter("Category_UID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Products_Select_Result>("Products_Select", category_UIDParameter);
        }
    }
}
