<?xml version="1.0" encoding="utf-8"?><Database Name="Galery" Class="PhotoDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DRWEB86-NOTE\SQLEXPRESS;Initial Catalog=Galery;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GaleryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Photo" Member="Photos">
    <Type Name="Photo">
      <Column Name="Photo_UID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>